---
- hosts: localhost
  gather_facts: False
  become: no
  roles:
    - etcd-ca

- hosts: all
  become: yes
  roles:
    - common
    - wireguard
    - k3s

- hosts: wgpublic
  roles:
    - wireguard/public

- hosts: wgprivate
  roles:
    - wireguard/private

- hosts: etcd
  become: yes
  roles:
    - etcd

- hosts: master
  become: yes
  roles:
    - k3s/master

- hosts: nodes
  become: yes
  roles:
    - k3s/node

...
