---
- hosts: all
  roles:
    - common
    - wireguard
    - k3s

- hosts: wgpublic
  roles:
    - wireguard/public

- hosts: wgprivate
  roles:
    - wireguard/private

- hosts: master
  roles:
    - k3s/master

- hosts: nodes
  roles:
    - k3s/node

...
