---

- name: Create etcd config directory
  file:
    path: "{{ etcd_conf_dir }}"
    state: directory
  tags:
    - etcd

- name: Create etcd download directory
  file:
    path: "{{ etcd_download_dir }}"
    state: directory
  tags:
    - etcd

- name: Create etcd bin directory
  file:
    path: "{{ etcd_bin_dir }}"
    state: directory
  tags:
    - etcd

- name: Create etcd data directory
  file:
    path: "{{ etcd_data_dir }}"
    state: directory
    mode: 0700
  tags:
    - etcd

- name: Download etcd
  get_url:
    url: "https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar"
    dest: "{{ etcd_download_dir }}/etcd-v{{ etcd_version }}-linux-amd64.tar"
    mode: 0755
  tags:
    - etcd
    - skip_ansible_lint

- name: Install unzipping packages
  dnf:
    name:
    - tar
    - unzip
    state: latest

- name: Unzip downloaded file
  unarchive:
    src: "{{ etcd_download_dir }}/etcd-v{{ etcd_version }}-linux-amd64.tar"
    dest: "{{ etcd_download_dir }}/"
    remote_src: yes
    owner: "root"
    group: "root"
    creates: "{{ etcd_download_dir }}/etcd-v{{ etcd_version }}-linux-amd64/etcd"
  tags:
    - etcd

- name: Copy etcd binaries to destination directory
  copy:
    src: "{{ etcd_download_dir }}/etcd-v{{ etcd_version }}-linux-amd64/{{ item }}"
    dest: "{{ etcd_bin_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
    remote_src: yes
  with_items:
    - etcd
    - etcdctl
  tags:
    - etcd

- name: Create systemd unit file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
  tags:
    - etcd
    - etcd-systemd

- meta: flush_handlers

- name: Enable and start etcd
  service:
    name: etcd
    enabled: yes
    state: started
  tags:
    - etcd

...
