---

- name: Restart wireguard
  service:
    name: "wg-quick@{{ wireguard_interface }}"
    state: "{{ item }}"
  loop:
  - stopped
  - started
  when: >
    not wg_syncconf
  listen: "reconfigure wireguard"

- name: Sync wireguard configuration
  shell: |
      set -o errexit
      set -o pipefail
      set -o nounset
      systemctl is-active wg-quick@{{ wireguard_interface|quote }} || systemctl start wg-quick@{{ wireguard_interface|quote }}
      wg syncconf {{ wireguard_interface|quote }} <(wg-quick strip /etc/wireguard/{{ wireguard_interface|quote }}.conf)
      exit 0
  args:
    executable: "/bin/bash"
  when: >
    wg_syncconf
  listen: "reconfigure wireguard"

- name: Reload firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: reloaded
  listen: "reconfigure firewall"

...
