---

- name: Restart wireguard
  service:
    name: "wg-quick@{{ wireguard_interface }}"
    state: restarted
  listen: "reconfigure wireguard"

- name: Reload firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: reloaded
  listen: "reconfigure firewall"

...
