---

- name: Run dotfiles
  command:
    cmd: /root/.dotfiles/bin/dotfiles

- name: Reload firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: reloaded
  listen: "reconfigure firewall"
