---

- name: Generate WireGuard configuration file
  template:
    src: wg-public.conf.j2
    dest: "{{ wireguard_remote_directory }}/{{ wireguard_interface }}.conf"
    owner: "{{ wireguard_conf_owner }}"
    group: "{{ wireguard_conf_group }}"
    mode: "{{ wireguard_conf_mode }}"
  tags:
    - wg-config
  notify:
    - reconfigure wireguard

# Service [[[1
- name: Start and enable Wireguard service
  service:
    name: "wg-quick@{{ wireguard_interface }}"
    state: started
    enabled: yes

