---

- name: Install firewalld
  dnf:
    name: firewalld
    state: latest

- name: Start firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Configure default zone
  ansible.posix.firewalld:
    zone: "{{ firewalld_default_zone }}"
    state: enabled
    interface: "{{ public_interface }}"
    permanent: yes
  notify:
    - reconfigure firewall

- name: Open k3s agent port to external
  ansible.posix.firewalld:
    zone: "{{ firewalld_default_zone }}"
    port: 6443/tcp
    permanent: yes
    state: enabled
  notify:
    - reconfigure firewall

- name: Open masquerade
  ansible.posix.firewalld:
    zone: "{{ firewalld_default_zone }}"
    state: enabled
    masquerade: 'yes'
    permanent: yes
  notify:
    - reconfigure firewall

- name: Open wireguard port
  ansible.posix.firewalld:
    zone: "{{ firewalld_default_zone }}"
    state: enabled
    port: 51820/udp
    permanent: yes
  notify:
    - reconfigure firewall

- name: Configure internal zone
  ansible.posix.firewalld:
    zone: internal
    state: enabled
    interface: wg0
    permanent: yes
  notify:
    - reconfigure firewall

- name: Open masquerade on wireguard
  ansible.posix.firewalld:
    zone: internal
    state: enabled
    masquerade: 'yes'
    permanent: yes
  notify:
    - reconfigure firewall

- name: Open k3s and etcd ports
  ansible.posix.firewalld:
    zone: internal
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 6443/tcp
    - 8472/udp
    - 10250/tcp
    - 2379-2380/tcp
  notify:
    - reconfigure firewall

...
