---
- name: Common packages
  dnf:
    name:
    - net-tools
    - gdisk
    state: present

- name: Run firewall tasks
  include: firewall.yml

- name: Run fail2ban tasks
  include: fail2ban.yml

- name: Run Rook tasks
  include: rook.yml

...
