---

- name: Install common packages
  dnf:
    name:
    - git
    - tmux
    - vim
    - zsh
    state: latest

- name: Deploy dotfiles
  become: no
  shell: "[ -d \"$HOME/.dotfiles\" ] || (git clone https://github.com/jdloft/dotfiles.git ~/.dotfiles && ~/.dotfiles/bin/dotfiles)"
  ignore_errors: yes

- name: Set zsh as shell
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh

- name: Run firewall tasks
  include: firewall.yml

...
