---

- name: Install common packages
  dnf:
    name:
    - git
    - tmux
    - vim
    - zsh
    state: latest

- name: Deploy dotfiles
  git:
    repo: 'https://github.com/jdloft/dotfiles.git'
    dest: /root/.dotfiles
    update: no
  notify:
    - Run dotfiles

- name: Set zsh as shell
  user:
    name: root
    shell: /usr/bin/zsh

- name: Run firewall tasks
  include: firewall.yml

...
