---
- name: "Create certs dir"
  file:
    path: ./certs
    state: directory

- name: "Generate private key for each member"
  openssl_privatekey:
    path: ./certs/{{ item }}.key
    type: RSA
    size: 4096
    state: present
    # force: True
  with_items: "{{ groups['etcd-access'] }}"

- name: "Generate private key for cluster access"
  openssl_privatekey:
    path: ./certs/cluster.key
    type: RSA
    size: 4096
    state: present

- name: "Generate CSR for each member"
  openssl_csr:
    path: ./certs/{{ item }}.csr
    privatekey_path: ./certs/{{ item }}.key
    common_name: "{{ item }}"
    key_usage:
      - digitalSignature
    extended_key_usage:
      - serverAuth
      - clientAuth
    subject_alt_name:
      - IP:{{ hostvars[item]['node_ip'] }}
      - IP:{{ hostvars[item]['node_external_ip'] }}
      - IP:127.0.0.1
    # force: True
  with_items: "{{ groups['etcd-access'] }}"

- name: "Generate CSR for cluster"
  openssl_csr:
    path: ./certs/cluster.csr
    privatekey_path: ./certs/cluster.key
    common_name: "localhost"
    key_usage:
      - digitalSignature
    extended_key_usage:
      - serverAuth
      - clientAuth
    subject_alt_name:
      - IP:127.0.0.1
      - DNS:localhost

- name: "Generate private key for CA"
  openssl_privatekey:
    path: ./certs/ca.key
    type: RSA
    size: 4096
    state: present
    # force: True

- name: "Generate CSR for CA"
  openssl_csr:
    path: ./certs/ca.csr
    privatekey_path: ./certs/ca.key
    common_name: ca
    organization_name: "etcd CA"
    basic_constraints:
      - CA:TRUE
      - pathlen:1
    basic_constraints_critical: True
    key_usage:
      - keyCertSign
      - digitalSignature
    # force: True

- name: "Generate self-signed CA certificate"
  openssl_certificate:
    path: ./certs/ca.crt
    privatekey_path: ./certs/ca.key
    csr_path: ./certs/ca.csr
    provider: selfsigned
    # force: True

- name: "Generate an `etcd` member certificate signed with our own CA certificate"
  openssl_certificate:
    path: ./certs/{{ item }}.crt
    csr_path: ./certs/{{ item }}.csr
    ownca_path: ./certs/ca.crt
    ownca_privatekey_path: ./certs/ca.key
    provider: ownca
    # force: True
  with_items: "{{ groups['etcd-access'] }}"

- name: "Generate an cluster certificate"
  openssl_certificate:
    path: ./certs/cluster.crt
    csr_path: ./certs/cluster.csr
    ownca_path: ./certs/ca.crt
    ownca_privatekey_path: ./certs/ca.key
    provider: ownca
