---

- name: Create etcd config directory
  file:
    path: "{{ etcd_conf_dir }}/ssl"
    state: directory
    recurse: yes
  tags:
    - etcd

- name: "Copy etcd CA certificate"
  copy:
    src: ./certs/ca.crt
    remote_src: no
    dest: "{{ etcd_conf_dir }}/ssl/ca.crt"
    owner: root
    group: root
    mode: 0644

- name: Copy etcd SSL cert
  copy:
    src: ./certs/{{ inventory_hostname }}.crt
    remote_src: no
    dest: "{{ etcd_conf_dir }}/ssl/server.crt"
    owner: root
    group: root
    mode: 0644

- name: Copy etcd SSL key
  copy:
    src: ./certs/{{ inventory_hostname }}.key
    remote_src: no
    dest: "{{ etcd_conf_dir }}/ssl/server.key"
    owner: root
    group: root
    mode: 0600

