---

- name: Set extra server args
  set_fact:
    extra_agent_args: "--node-ip={{ node_ip }} --node-external-ip={{ node_external_ip }} --flannel-iface={{ wireguard_interface }}"

- name: Copy k3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755
  notify:
    - reconfigure k3s

- name: Enable and start k3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: started
    enabled: yes
